Repository GergelyKamaras/Filc, pull requests merged in 2022-12, with the labels that each got.

#105 Style index page
  Filc/ClientApp/package-lock.json
  Filc/ClientApp/package.json
  Filc/ClientApp/src/App.js
  Filc/ClientApp/src/DataFetches/LoginApiFetch.js
  Filc/ClientApp/src/Pages/AppIndex.js
  Filc/ClientApp/src/Pages/LoginPage.js
  Filc/ClientApp/src/Style/IndexPage/IndexPage.css
  Filc/ClientApp/src/Style/IndexPage/InnerGovNews.css
  Filc/ClientApp/src/Style/IndexPage/InnerProfil.css
  Filc/ClientApp/src/Style/IndexPage/SignIn.css
  Filc/ClientApp/src/Style/navbar.css
  Filc/ClientApp/src/components/Header.js
  Filc/ClientApp/src/components/IndexPageComponents/InnerProfil.js
  Filc/ClientApp/src/components/IndexPageComponents/News.js
  Filc/ClientApp/src/components/IndexPageComponents/SignInBox.js
  Filc/ClientApp/src/components/LoggedInCheck.js
  Filc/ClientApp/src/components/controllers/LoginApiFetch.js
Labels: documentation, enhancement

#106 create frontend display for db data
  Filc/ClientApp/src/components/UserComponents/GovAdminComponents/Components/AddSchool.js
  Filc/ClientApp/src/components/UserComponents/GovAdminComponents/Components/School.js
  Filc/ClientApp/src/components/UserComponents/GovAdminComponents/Components/SchoolAdmin.js
  Filc/ClientApp/src/components/UserComponents/GovAdminComponents/Components/Schools.js
  Filc/ClientApp/src/components/UserComponents/GovAdminComponents/Controllers/SchoolAdminFetchById.js
Labels: react

#126 Refactor login backend
  Filc/Controllers/AccountController.cs
  Filc/Controllers/Apis/GovernmentAdminApiController.cs
  Filc/Controllers/Apis/SchoolAdminApiController.cs
  Filc/Models/AuthenticationModels/RegistrationModel.cs
  Filc/Program.cs
  Filc/Services/DataBaseQueryServices/GovernmentAdminTableQueryService.cs
  Filc/Services/DataBaseQueryServices/SchoolAdminTableQueryService.cs
  Filc/Services/Interfaces/IJwtTokenGenerator.cs
  Filc/Services/Interfaces/ILogin.cs
  Filc/Services/Interfaces/IRegistration.cs
  Filc/Services/Interfaces/RoleBasedInterfacesForApis/FullAccess/IGovernmentAdminServiceFullAccess.cs
  Filc/Services/Interfaces/RoleBasedInterfacesForApis/SchoolAdminRole/ISchoolAdminServiceForSchoolAdminRole.cs
  Filc/Services/JwtTokenGeneratorService.cs
  Filc/Services/LoginService.cs
  Filc/Services/RegistrationService.cs
Labels: asp.net

#147 Refactor home page with login form
  Filc/ClientApp/src/Pages/Home/AppIndex.js
  Filc/ClientApp/src/Pages/Home/InnerProfil.js
  Filc/ClientApp/src/Pages/Login/FetchHashedPassword.js
  Filc/ClientApp/src/Pages/Login/LoginUser.js
  Filc/Controllers/Apis/LoginController.cs
  Filc/Models/AuthenticationModels/EmailModel.cs
  Filc/Services/DataBaseQueryServices/GovernmentAdminTableQueryService.cs
Labels: bug, react

#151 Register parent add dropdown with fetchallstudents
  Filc/ClientApp/src/Pages/Registration/RegisterParent.js
  Filc/ClientApp/src/Pages/Registration/RegistrationForm.js
  Filc/ClientApp/src/Pages/Students/FetchAllStudents.js
Labels: react

#156 React read fetch data show in table element
  Filc/ClientApp/package-lock.json
  Filc/ClientApp/package.json
  Filc/ClientApp/src/App.js
  Filc/ClientApp/src/Pages/ListData.js
  Filc/ClientApp/src/Pages/globalFilter.js
  Filc/ClientApp/src/Pages/table.css
  Filc/package-lock.json
  Filc/package.json
Labels: react

#163 Add: GovernmentAdmin routes with links
  Filc/ClientApp/src/App.js
  Filc/ClientApp/src/Pages/ListData.js
  Filc/Controllers/Apis/SchoolAdminApiController.cs
Labels: react
